export const PATH = {
  ROOT: '/',
  ACCOUNT_PERMANENT_SUSPENDED: '/account-permanent-suspended',
  LOGIN: {
    BASE: '/login',
    KAKAO: 'kakao',
  },
  SIGNUP: {
    BASE: '/signup',
    TERMS: 'terms',
    WELCOME: 'welcome',
    PROFILE: 'profile',
    SCHOOL: 'school',
    VERIFY: {
      BASE: 'verify',
      EMAIL: 'email',
      FILE: 'file',
    },
  },
  BOARD: {
    BASE: '/board',
    SPECIFIC: {
      BASE: ':boardId',
      TRENDING: 'trending',
      WRITE: 'write',
      EDIT: 'edit',
      POST: ':postId',
      REPORT: 'report',
      DRAFT: 'draft',
      SEARCH: 'search',
    },
  },
  HOME: '/home',
  SEARCH: '/search',
  BOARD_GUIDE: '/boardGuide',
  MYPAGE: {
    BASE: '/my',
    VERIFY: {
      FAIL: 'verify/fail',
    },
    SETTINGS: {
      INFO: 'settings/info',
      VERIFICATION: 'settings/verification',
    },
    COMMUNITY: {
      BASE: 'community',
      SCRAP: {
        BASE: 'scrap',
        COMMUNITY: 'community',
        MARKET: 'market',
      },
      ARTICLE: {
        BASE: 'article',
        ARTICLES: 'articles',
        COMMENTS: 'comments',
        MARKET: 'markets',
      },
      MARKET: 'market',
    },
    SERVICE: {
      BASE: 'contactUs',
      FAQ: 'faq',
      INQUIRY: 'inquiry',
      INQUIRY_DETAILS: ':inquiryId',
      WRITE_INQUIRY: 'write',
      NOTICE: 'notice',
      NOTICE_DETAILS: ':noticeId',
    },
    BLOCK: {
      BASE: 'block',
      CHAT: 'chat',
      MARKET: 'market',
    },
    DELETE: 'leave',
  },
  MARKET: {
    BASE: '/market',
    WRITE: 'write',
    EDIT: 'edit',
    PRODUCT: ':productId',
    SEARCH: 'search',
  },
  CHAT_LIST: {
    BASE: '/chat',
    REPORT: 'report',
  },
  ADMIN: {
    BASE: '/admin',
    LOGIN: 'login',
    DASHBOARD: 'dashboard',
    USER_MANAGEMENT: 'userManagement',
    CATEGORY: 'category',
    SIGNUP_MANAGEMENT: {
      BASE: 'signupManagement',
      STUDENT_VERIFICATIONS: ':verificationRecordId',
    },
    BOARD_MANAGEMENT: {
      BASE: 'boardManagement',
      CREATE: 'create',
      BOARD_ID: ':boardId',
      EDIT: 'edit',
    },
    CARDNEWS: {
      BASE: 'cardnews',
      CREATE: 'create',
      CARDNEWS_ID: ':cardnewsId',
      EDIT: 'edit',
    },
    REPORT_MANAGEMENT: 'reportMangement',
    STATISTICS: 'statistics',
    NOTICE: {
      BASE: 'notice',
      CREATE: 'create',
      NOTICE_ID: ':noticeId',
      EDIT: 'edit',
    },
  },
};
