export const path = {
  root: '/',
  accountPermanentSuspended: '/account-permanent-suspended',
  login: {
    base: '/login',
    kakao: 'kakao',
  },
  signup: {
    base: '/signup',
    terms: 'terms',
    welcome: 'welcome',
    profile: 'profile',
    school: 'school',
    verify: {
      base: 'verify',
      email: 'email',
      file: 'file',
    },
  },
  board: {
    base: '/board',
    specific: {
      base: ':boardId',
      write: 'write',
      edit: 'edit',
      post: ':postId',
      report: 'report',
      draft: 'draft',
      search: 'search',
    },
  },
  home: '/home',
  search: '/search',
  boardGuide: '/boardGuide',
  mypage: {
    base: '/my',
    verify: {
      fail: 'verify/fail',
    },
    settings: {
      info: 'settings/info',
      verification: 'settings/verification',
    },
    community: {
      base: 'community',
      scrap: {
        base: 'scrap',
        community: 'community',
        market: 'market',
      },
      article: {
        base: 'article',
        articles: 'articles',
        comments: 'comments',
        market: 'markets',
      },
      market: 'market',
    },
    service: {
      base: 'contactUs',
      faq: 'faq',
      inquiry: 'inquiry',
      inquiryDetails: ':inquiryId',
      writeInquiry: 'write',
      notice: 'notice',
      noticeDetails: ':noticeId',
    },
    block: {
      base: 'block',
      chat: 'chat',
      market: 'market',
    },
    delete: 'leave',
  },
  market: {
    base: '/market',
    write: 'write',
    edit: 'edit',
    product: ':productId',
  },
  chatList: {
    base: '/chat',
    report: 'report',
  },
  admin: {
    base: '/admin',
    login: 'login',
    dashboard: 'dashboard',
    userManagement: 'userManagement',
    category: 'category',
    signupManagement: {
      base: 'signupManagement',
      studentVertifications: ':verificationRecordId',
    },
    boardManagement: {
      base: 'boardManagement',
      create: 'create',
      boardId: ':boardId',
      edit: 'edit',
    },
    cardnews: {
      base: 'cardnews',
      create: 'create',
      cardnewsId: ':cardnewsId',
      edit: 'edit',
    },
    reportMangement: 'reportMangement',
    statistics: 'statistics',
    notice: {
      base: 'notice',
      create: 'create',
      noticeId: ':noticeId',
      edit: 'edit',
    },
  },
};
