export const BOARD_TYPE = {
  FIXED: 'FIXED',
  TRENDING: 'TRENDING',
  NORMAL: 'NORMAL',
  CARD: 'CARDNEWS',
  UNIV: 'UNIVERSITY',
};
export const BOARD_STATE = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING_DELETION',
};
