export const Languages = [
  { name: 'Arabic', code: 'AR' },
  { name: 'Bulgarian', code: 'BG' },
  { name: 'Czech', code: 'CS' },
  { name: 'Danish', code: 'DA' },
  { name: 'German', code: 'DE' },
  { name: 'Greek', code: 'EL' },
  { name: 'English (British)', code: 'EN-GB' },
  { name: 'English (American)', code: 'EN-US' },
  { name: 'Spanish', code: 'ES' },
  { name: 'Estonian', code: 'ET' },
  { name: 'Finnish', code: 'FI' },
  { name: 'French', code: 'FR' },
  { name: 'Hungarian', code: 'HU' },
  { name: 'Indonesian', code: 'ID' },
  { name: 'Italian', code: 'IT' },
  { name: 'Japanese', code: 'JA' },
  { name: 'Korean', code: 'KO' },
  { name: 'Lithuanian', code: 'LT' },
  { name: 'Latvian', code: 'LV' },
  { name: 'Norwegian Bokmål', code: 'NB' },
  { name: 'Dutch', code: 'NL' },
  { name: 'Polish', code: 'PL' },
  { name: 'Portuguese (Brazilian)', code: 'PT-BR' },
  { name: 'Portuguese', code: 'PT-PT' },
  { name: 'Romanian', code: 'RO' },
  { name: 'Russian', code: 'RU' },
  { name: 'Slovak', code: 'SK' },
  { name: 'Slovenian', code: 'SL' },
  { name: 'Swedish', code: 'SV' },
  { name: 'Turkish', code: 'TR' },
  { name: 'Ukrainian', code: 'UK' },
  { name: 'Chinese (simplified)', code: 'ZH-HANS' },
  { name: 'Chinese (traditional)', code: 'ZH-HANT' },
];

export default Languages;
