const University = [
  { code: '가야대학교', name: 'Kaya University' },
  { code: '가천길대학교', name: 'Gachon-gil University' },
  { code: '가천대학교', name: 'Gachon University' },
  { code: '가천의과학대학교', name: 'Gachon University of Medical Science' },
  { code: '가톨릭관동대학교', name: 'Catholic Kwandong University' },
  { code: '가톨릭대학교', name: 'Catholic University of Korea' },
  { code: '가톨릭상지대학교', name: 'Catholic Sangji University' },
  { code: '감리교신학대학교', name: 'Methodist Theological University' },
  { code: '강남대학교', name: 'Kangnam University' },
  { code: '강동대학교', name: 'Kangdong University' },
  { code: '강릉영동대학교', name: 'Gangneung-Yeongdong University' },
  { code: '강릉원주대학교', name: 'Gangneung-Wonju National University' },
  { code: '강원관광대학교', name: 'Gangwon Tourism University' },
  { code: '강원대학교', name: 'Kangwon National University' },
  { code: '강원도립대학교', name: 'Gangwon Provincial University' },
  { code: '거제대학교', name: 'Geoje University' },
  { code: '건국대학교', name: 'Konkuk University' },
  { code: '건국대학교(글로컬)', name: 'Konkuk University (GLOCAL Campus)' },
  { code: '건양대학교', name: 'Konyang University' },
  { code: '건양사이버대학교', name: 'Konyang Cyber University' },
  {
    code: '경기과학기술대학교',
    name: 'Gyeonggi University of Science and Technology',
  },
  { code: '경기대학교', name: 'Kyonggi University' },
  {
    code: '경남과학기술대학교',
    name: 'Gyeongnam National University of Science and Technology',
  },
  { code: '경남대학교', name: 'Kyungnam University' },
  { code: '경남도립거창대학교', name: 'Gyeongnam Provincial Geochang College' },
  { code: '경남도립남해대학교', name: 'Gyeongnam Provincial Namhae College' },
  {
    code: '경남정보대학교',
    name: 'Kyungnam College of Information & Technology',
  },
  { code: '경동대학교', name: 'Kyungdong University' },
  { code: '경민대학교', name: 'Kyungmin University' },
  { code: '경복대학교', name: 'Kyungbok University' },
  { code: '경북과학대학교', name: 'Kyungbuk Science College' },
  { code: '경북대학교', name: 'Kyungpook National University' },
  { code: '경북도립대학교', name: 'Kyungbuk Provincial College' },
  { code: '경북외국어대학교', name: 'Kyungbuk University of Foreign Studies' },
  { code: '경북전문대학교', name: 'Kyungbuk College of Science & Technology' },
  { code: '경산대학교', name: 'Kyungsan University' },
  { code: '경상대학교', name: 'Gyeongsang National University' },
  { code: '경성대학교', name: 'Kyungsung University' },
  { code: '경운대학교', name: 'Kyungwoon University' },
  {
    code: '경운대학교(산업대)',
    name: 'Kyungwoon University (Industry University)',
  },
  { code: '경원전문대학교', name: 'Kyungwon Professional College' },
  { code: '경인교육대학교', name: 'Gyeongin National University of Education' },
  { code: '경인여자대학교', name: "Kyungin Women's University" },
  { code: '경일대학교', name: 'Kyungil University' },
  { code: '경주대학교', name: 'Kyongju University' },
  { code: '경희대학교', name: 'Kyung Hee University' },
  { code: '경희사이버대학교', name: 'Kyung Hee Cyber University' },
  { code: '계명대학교', name: 'Keimyung University' },
  { code: '계명문화대학교', name: 'Keimyung College' },
  { code: '계원예술대학교', name: 'Kaywon University of Art & Design' },
  { code: '고구려대학교', name: 'Koguryeo University' },
  { code: '고려대학교', name: 'Korea University' },
  { code: '고려대학교(세종)', name: 'Korea University (Sejong Campus)' },
  { code: '고려사이버대학교', name: 'Korea Cyber University' },
  { code: '고신대학교', name: 'Kosin University' },
  { code: '공주교육대학교', name: 'Kongju National University of Education' },
  { code: '공주대학교', name: 'Kongju National University' },
  { code: '광신대학교', name: 'Kwangshin University' },
  { code: '광양보건대학교', name: 'Gwangyang Health University College' },
  { code: '광운대학교', name: 'Kwangwoon University' },
  { code: '광주가톨릭대학교', name: 'Gwangju Catholic University' },
  { code: '광주교육대학교', name: 'Gwangju National University of Education' },
  { code: '광주대학교', name: 'Gwangju University' },
  {
    code: '광주대학교(산업대)',
    name: 'Gwangju University (Industry University)',
  },
  { code: '광주보건대학교', name: 'Gwangju Health College' },
  { code: '광주여자대학교', name: "Gwangju Women's University" },
  { code: '구미대학교', name: 'Gumi University' },
  { code: '구세군사관학교', name: 'The Salvation Army College' },
  { code: '국민대학교', name: 'Kookmin University' },
  { code: '국제대학교', name: 'Kukje University' },
  { code: '국제사이버대학교', name: 'Korea National Cyber University' },
  { code: '군산간호대학교', name: 'Gunsan College of Nursing' },
  { code: '군산대학교', name: 'Gunsan National University' },
  { code: '군장대학교', name: 'Kunjang University' },
  { code: '그리스도대학교', name: 'Christ University' },
  { code: '극동대학교', name: 'Far East University' },
  { code: '글로벌사이버대학교', name: 'Global Cyber University' },
  { code: '금강대학교', name: 'Kumgang University' },
  { code: '금오공과대학교', name: 'Kumoh National Institute of Technology' },
  { code: '기독간호대학교', name: 'Christian College of Nursing' },
  { code: '김천과학대학교', name: 'Kimcheon Science College' },
  { code: '김천대학교', name: 'Kimcheon University' },
  { code: '김포대학교', name: 'Kimpo University' },
  { code: '김해대학교', name: 'Kimhae University' },
  { code: '꽃동네대학교', name: 'Kkottongnae University' },
  { code: '나사렛대학교', name: 'Nazarene University' },
  { code: '남부대학교', name: 'Nambu University' },
  { code: '남서울대학교', name: 'Namseoul University' },
  {
    code: '남서울대학교(산업대)',
    name: 'Namseoul University (Industry University)',
  },
  { code: '농협대학교', name: 'Nonghyup University' },
  { code: '단국대학교', name: 'Dankook University' },
  { code: '대경대학교', name: 'Daekyung University' },
  { code: '대구가톨릭대학교', name: 'Daegu Catholic University' },
  { code: '대구공업대학교', name: 'Daegu Polytechnic College' },
  { code: '대구과학대학교', name: 'Daegu Science University' },
  { code: '대구교육대학교', name: 'Daegu National University of Education' },
  { code: '대구대학교', name: 'Daegu University' },
  { code: '대구미래대학교', name: 'Daegu Future University' },
  { code: '대구보건대학교', name: 'Daegu Health College' },
  { code: '대구사이버대학교', name: 'Daegu Cyber University' },
  { code: '대구예술대학교', name: 'Daegu Arts University' },
  { code: '대구외국어대학교', name: 'Daegu University of Foreign Studies' },
  { code: '대구한의대학교', name: 'Daegu Haany University' },
  { code: '대덕대학교', name: 'Daedeok University' },
  { code: '대동대학교', name: 'Daedong University' },
  { code: '대림대학교', name: 'Daelim University College' },
  { code: '대신대학교', name: 'Daeshin University' },
  { code: '대원대학교', name: 'Daewon University' },
  { code: '대전가톨릭대학교', name: 'Daejeon Catholic University' },
  { code: '대전대학교', name: 'Daejeon University' },
  { code: '대전보건대학교', name: 'Daejeon Health College' },
  { code: '대전신학교', name: 'Daejeon Theological Seminary' },
  { code: '대전신학대학교', name: 'Daejeon Theological University' },
  { code: '대진대학교', name: 'Daejin University' },
  { code: '덕성여자대학교', name: "Duksung Women's University" },
  { code: '동강대학교', name: 'Dong-gang University' },
  { code: '동국대학교', name: 'Dongguk University' },
  { code: '동국대학교(경주)', name: 'Dongguk University (Gyeongju Campus)' },
  { code: '동남보건대학교', name: 'Dongnam Health University College' },
  { code: '동덕여자대학교', name: "Dongduk Women's University" },
  { code: '동명대학교', name: 'Dongmyung University' },
  { code: '동명정보대학교', name: 'Dongmyung Information University' },
  { code: '동부산대학교', name: 'Dongbusan University' },
  { code: '동서대학교', name: 'Dongseo University' },
  { code: '동서울대학교', name: 'Dongseoul University' },
  { code: '동신대학교', name: 'Dongshin University' },
  { code: '동아대학교', name: 'Dong-A University' },
  { code: '동아방송예술대학교', name: 'Dong-Ah Institute of Media and Arts' },
  {
    code: '동아인재대학교',
    name: 'Dong-A Human Resources Development University',
  },
  { code: '동양대학교', name: 'Dongyang University' },
  { code: '동양미래대학교', name: 'Dongyang Mirae University' },
  { code: '동우대학교', name: 'Dong-u University' },
  {
    code: '동원과학기술대학교',
    name: 'Dongwon Science and Technology University',
  },
  { code: '동원대학교', name: 'Dongwon University' },
  {
    code: '동의과학대학교',
    name: 'Dongeui University College of Science and Technology',
  },
  { code: '동의대학교', name: 'Dongeui University' },
  { code: '동주대학교', name: 'Dongju University' },
  { code: '두원공과대학교', name: 'Doowon Technical University College' },
  {
    code: '디지털서울문화예술대학교',
    name: 'Digital Seoul Culture Arts University',
  },
  { code: '루터대학교', name: 'Luther University' },
  { code: '마산대학교', name: 'Masan University' },
  { code: '명지대학교', name: 'Myongji University' },
  { code: '명지전문대학교', name: 'Myongji College' },
  { code: '목원대학교', name: 'Mokwon University' },
  { code: '목포가톨릭대학교', name: 'Mokpo Catholic University' },
  { code: '목포과학대학교', name: 'Mokpo Science University' },
  { code: '목포대학교', name: 'Mokpo National University' },
  { code: '목포해양대학교', name: 'Mokpo National Maritime University' },
  { code: '문경대학교', name: 'Mungyeong University' },
  { code: '배재대학교', name: 'Pai Chai University' },
  { code: '배화여자대학교', name: "Paiwha Women's University" },
  { code: '백석대학교', name: 'Baekseok University' },
  { code: '백석문화대학교', name: 'Baekseok Culture University' },
  { code: '백제예술대학교', name: 'Paekche University of Arts' },
  { code: '벽성대학교', name: 'Byeokseong University' },
  { code: '국립부경대학교', name: 'Pukyong National University' },
  { code: '부산가톨릭대학교', name: 'Catholic University of Busan' },
  { code: '부산경상대학교', name: 'Busan Gyeongnam University' },
  {
    code: '부산과학기술대학교',
    name: 'Busan University of Science and Technology',
  },
  { code: '부산교육대학교', name: 'Busan National University of Education' },
  { code: '부산대학교', name: 'Pusan National University' },
  { code: '부산디지털대학교', name: 'Busan Digital University' },
  { code: '부산여자대학교', name: "Busan Women's University" },
  { code: '부산예술대학교', name: 'Busan University of Arts' },
  { code: '부산외국어대학교', name: 'Busan University of Foreign Studies' },
  { code: '부산장신대학교', name: 'Busan Presbyterian Theological Seminary' },
  { code: '부천대학교', name: 'Bucheon University' },
  {
    code: '사이버한국외국어대학교',
    name: 'Cyber Hankuk University of Foreign Studies',
  },
  { code: '삼육대학교', name: 'Sahmyook University' },
  { code: '삼육보건대학교', name: 'Sahmyook Health University College' },
  { code: '삼육의명대학교', name: 'Sahmyook Myungji University' },
  { code: '상명대학교', name: 'Sangmyung University' },
  { code: '상명대학교(천안)', name: 'Sangmyung University (Cheonan Campus)' },
  { code: '상주대학교', name: 'Sangju University' },
  { code: '상지대학교', name: 'Sangji University' },
  { code: '상지영서대학교', name: 'Sangji Yeongseo University' },
  { code: '서강대학교', name: 'Sogang University' },
  { code: '서경대학교', name: 'Seokyeong University' },
  { code: '서남대학교', name: 'Seonam University' },
  { code: '서라벌대학교', name: 'Seorabeol University' },
  { code: '서영대학교', name: 'Seoyeong University' },
  {
    code: '서울과학기술대학교',
    name: 'Seoul National University of Science and Technology',
  },
  {
    code: '서울과학기술대학교(산업대)',
    name: 'Seoul National University of Science and Technology (Industry University)',
  },
  { code: '서울교육대학교', name: 'Seoul National University of Education' },
  { code: '서울기독대학교', name: 'Seoul Christian University' },
  { code: '서울대학교', name: 'Seoul National University' },
  { code: '서울디지털대학교', name: 'Seoul Digital University' },
  { code: '서울보건대학교', name: 'Seoul Health University' },
  { code: '서울사이버대학교', name: 'Seoul Cyber University' },
  { code: '서울시립대학교', name: 'University of Seoul' },
  { code: '서울신학대학교', name: 'Seoul Theological University' },
  { code: '서울여자간호대학교', name: "Seoul Women's University of Nursing" },
  { code: '서울여자대학교', name: "Seoul Women's University" },
  { code: '서울예술대학교', name: 'Seoul Institute of the Arts' },
  { code: '서울장신대학교', name: 'Seoul Presbyterian Theological Seminary' },
  { code: '서원대학교', name: 'Seowon University' },
  { code: '서일대학교', name: 'Seoil University' },
  { code: '서정대학교', name: 'Seojeong University' },
  { code: '서해대학교', name: 'Seohae University' },
  { code: '선린대학교', name: 'Sunrin University' },
  { code: '선문대학교', name: 'Sun Moon University' },
  { code: '성결대학교', name: 'Sungkyul University' },
  { code: '성공회대학교', name: 'Anglican University' },
  { code: '성균관대학교', name: 'Sungkyunkwan University' },
  { code: '성덕대학교', name: 'Sungduk University' },
  { code: '성신여자대학교', name: "Sungshin Women's University" },
  {
    code: '성심외국어대학교',
    name: 'Sacred Heart University of Foreign Studies',
  },
  { code: '세경대학교', name: 'Saekyung University' },
  { code: '세명대학교', name: 'Semyung University' },
  { code: '세종대학교', name: 'Sejong University' },
  { code: '세종사이버대학교', name: 'Sejong Cyber University' },
  { code: '세한대학교', name: 'Sehan University' },
  { code: '송곡대학교', name: 'Songgok University' },
  { code: '송원대학교', name: 'Songwon University' },
  { code: '송호대학교', name: 'Songho University' },
  { code: '수성대학교', name: 'Suseong University' },
  { code: '수원가톨릭대학교', name: 'Suwon Catholic University' },
  { code: '수원과학대학교', name: 'Suwon Science College' },
  { code: '수원대학교', name: 'University of Suwon' },
  { code: '수원여자대학교', name: "Suwon Women's University" },
  { code: '숙명여자대학교', name: "Sookmyung Women's University" },
  { code: '순복음총회신학교', name: 'Full Gospel Theological Seminary' },
  { code: '순천대학교', name: 'Sunchon National University' },
  { code: '순천제일대학교', name: 'Sunchon First University' },
  { code: '순천향대학교', name: 'Soonchunhyang University' },
  { code: '숭실대학교', name: 'Soongsil University' },
  { code: '숭실사이버대학교', name: 'Soongsil Cyber University' },
  { code: '숭의여자대학교', name: "Sungui Women's University" },
  { code: '신경대학교', name: 'Shin Kyoung University' },
  { code: '신구대학교', name: 'Shingu University' },
  { code: '신라대학교', name: 'Silla University' },
  { code: '신성대학교', name: 'Sinsung University' },
  { code: '신안산대학교', name: 'Shin Ansan University' },
  { code: '신흥대학교', name: 'Shinheung University' },
  { code: '아세아연합신학대학교', name: 'Asia United Theological University' },
  { code: '아주대학교', name: 'Ajou University' },
  { code: '아주자동차대학교', name: 'Ajou Motor College' },
  { code: '안동과학대학교', name: 'Andong Science University' },
  { code: '안동대학교', name: 'Andong National University' },
  { code: '안산대학교', name: 'Ansan University' },
  { code: '안양대학교', name: 'Anyang University' },
  { code: '여주대학교', name: 'Yeoju University' },
  { code: '연성대학교', name: 'Yeonseong University' },
  { code: '연세대학교', name: 'Yonsei University' },
  { code: '연세대학교(원주)', name: 'Yonsei University (Wonju Campus)' },
  { code: '연암공과대학교', name: 'Yeonam Institute of Technology' },
  { code: '열린사이버대학교', name: 'Korea Open Cyber University' },
  { code: '영남대학교', name: 'Yeungnam University' },
  { code: '영남신학대학교', name: 'Yeungnam Theological Seminary' },
  { code: '영남외국어대학교', name: 'Yeungnam University of Foreign Studies' },
  {
    code: '영남이공대학교',
    name: 'Yeungnam University College of Engineering',
  },
  { code: '영산대학교', name: 'Youngsan University' },
  {
    code: '영산대학교(산업대)',
    name: 'Youngsan University (Industry University)',
  },
  { code: '영산선학대학교', name: 'Youngsan Seonhak University' },
  { code: '영진사이버대학교', name: 'Yeongjin Cyber University' },
  { code: '영진전문대학교', name: 'Yeongjin Professional University' },
  { code: '예수대학교', name: 'Jesus University' },
  { code: '예원예술대학교', name: 'Yewon Arts University' },
  { code: '오산대학교', name: 'Osan University' },
  { code: '용인대학교', name: 'Yongin University' },
  { code: '용인송담대학교', name: 'Yongin Songdam College' },
  { code: '우석대학교', name: 'Woosuk University' },
  { code: '우송공업대학교', name: 'Woosong College of Industry' },
  { code: '우송대학교', name: 'Woosong University' },
  {
    code: '우송대학교(산업대)',
    name: 'Woosong University (Industry University)',
  },
  { code: '우송정보대학교', name: 'Woosong Information University' },
  { code: '울산과학대학교', name: 'Ulsan College of Science' },
  { code: '울산대학교', name: 'University of Ulsan' },
  { code: '웅지세무대학교', name: 'Ungji Tax University' },
  { code: '원광대학교', name: 'Wonkwang University' },
  { code: '원광디지털대학교', name: 'Wonkwang Digital University' },
  { code: '원광보건대학교', name: 'Wonkwang Health Science College' },
  { code: '원주대학교', name: 'Wonju University' },
  { code: '위덕대학교', name: 'Wideok University' },
  { code: '유원대학교', name: 'Uwon University' },
  { code: '유한대학교', name: 'Yuhan University' },
  { code: '을지대학교', name: 'Eulji University' },
  { code: '이화여자대학교', name: 'Ewha Womans University' },
  { code: '인덕대학교', name: 'Induk University' },
  { code: '인제대학교', name: 'Inje University' },
  { code: '인천가톨릭대학교', name: 'Incheon Catholic University' },
  { code: '인천대학교', name: 'Incheon National University' },
  { code: '인천재능대학교', name: 'Incheon JaeNeung University' },
  { code: '인천전문대학교', name: 'Incheon Professional College' },
  { code: '인하공업전문대학교', name: 'Inha Technical College' },
  { code: '인하대학교', name: 'Inha University' },
  { code: '장로회신학대학교', name: 'Presbyterian Theological Seminary' },
  { code: '장안대학교', name: 'Jangan University' },
  { code: '적십자간호대학교', name: 'Red Cross College of Nursing' },
  { code: '전남과학대학교', name: 'Jeonnam Science University' },
  { code: '전남대학교', name: 'Chonnam National University' },
  { code: '전남도립대학교', name: 'Jeonnam Provincial College' },
  { code: '전북과학대학교', name: 'Jeonbuk Science College' },
  { code: '전북대학교', name: 'Jeonbuk National University' },
  { code: '전주교육대학교', name: 'Jeonju National University of Education' },
  { code: '전주기전대학교', name: 'Jeonju Kijeon University' },
  { code: '전주대학교', name: 'Jeonju University' },
  { code: '전주비전대학교', name: 'Jeonju Vision University' },
  { code: '정석대학교', name: 'Jungseok University' },
  { code: '제주관광대학교', name: 'Jeju Tourism University' },
  { code: '제주교육대학교', name: 'Jeju National University of Education' },
  { code: '제주국제대학교', name: 'Jeju International University' },
  { code: '제주대학교', name: 'Jeju National University' },
  {
    code: '제주산업정보대학교',
    name: 'Jeju Industrial Information University',
  },
  { code: '제주한라대학교', name: 'Jeju Halla University' },
  { code: '조선간호대학교', name: 'Chosun Nursing College' },
  { code: '조선대학교', name: 'Chosun University' },
  { code: '조선이공대학교', name: 'Chosun College of Science and Technology' },
  { code: '중부대학교', name: 'Joongbu University' },
  { code: '중앙대학교', name: 'Chung-Ang University' },
  { code: '중앙대학교(안성)', name: 'Chung-Ang University (Anseong Campus)' },
  { code: '중앙승가대학교', name: 'Central Sangha University' },
  { code: '중원대학교', name: 'Jungwon University' },
  { code: '진주교육대학교', name: 'Jinju National University of Education' },
  { code: '진주보건대학교', name: 'Jinju Health College' },
  {
    code: '진주산업대학교(산업대)',
    name: 'Jinju Industrial University (Industry University)',
  },
  { code: '차의과학대학교', name: 'CHA University' },
  { code: '창신대학교', name: 'Changshin University' },
  { code: '창원대학교', name: 'Changwon National University' },
  { code: '창원문성대학교', name: 'Changwon Moonsung University' },
  { code: '천안연암대학교', name: 'Cheonan Yeonam University' },
  {
    code: '청강문화산업대학교',
    name: 'Chungkang College of Cultural Industries',
  },
  { code: '청암대학교', name: 'Cheongam University' },
  { code: '청운대학교', name: 'Chungwoon University' },
  { code: '청주교육대학교', name: 'Cheongju National University of Education' },
  { code: '청주대학교', name: 'Cheongju University' },
  { code: '초당대학교', name: 'Chodang University' },
  {
    code: '초당대학교(산업대)',
    name: 'Chodang University (Industry University)',
  },
  { code: '총신대학교', name: 'Chongshin University' },
  { code: '추계예술대학교', name: 'Chugye University for the Arts' },
  {
    code: '춘천교육대학교',
    name: 'Chuncheon National University of Education',
  },
  { code: '춘해보건대학교', name: 'Chunhae Health University College' },
  { code: '충남대학교', name: 'Chungnam National University' },
  {
    code: '충남도립청양대학교',
    name: 'Chungnam Provincial Cheongyang College',
  },
  { code: '충북대학교', name: 'Chungbuk National University' },
  { code: '충북도립대학교', name: 'Chungbuk Provincial University' },
  {
    code: '충북보건과학대학교',
    name: 'Chungbuk Health Science University College',
  },
  { code: '충청대학교', name: 'Chungcheong University' },
  { code: '침례신학대학교', name: 'Baptist Theological Seminary' },
  { code: '칼빈대학교', name: 'Calvin University' },
  { code: '탐라대학교', name: 'Tamra University' },
  { code: '평택대학교', name: 'Pyeongtaek University' },
  { code: '포항대학교', name: 'Pohang University' },
  { code: '한경대학교', name: 'Hankyong National University' },
  {
    code: '한경대학교(산업대)',
    name: 'Hankyong National University (Industry University)',
  },
  { code: '한국골프대학교', name: 'Korea Golf University' },
  { code: '한국관광대학교', name: 'Korea Tourism University' },
  { code: '한국교원대학교', name: 'Korea National University of Education' },
  {
    code: '한국교통대학교',
    name: 'Korea National University of Transportation',
  },
  {
    code: '한국교통대학교(산업대)',
    name: 'Korea National University of Transportation (Industry University)',
  },
  { code: '한국국제대학교', name: 'Korea International University' },
  {
    code: '한국기술교육대학교',
    name: 'Korea University of Technology and Education',
  },
  {
    code: '한국농수산대학교',
    name: 'Korea National College of Agriculture and Fisheries',
  },
  { code: '한국방송통신대학교', name: 'Korea National Open University' },
  { code: '한국복지대학교', name: 'Korea Welfare University' },
  { code: '한국복지사이버대학교', name: 'Korea Welfare Cyber University' },
  { code: '한국산업기술대학교', name: 'Korea Polytechnic University' },
  {
    code: '한국산업기술대학교(산업대)',
    name: 'Korea Polytechnic University (Industry University)',
  },
  { code: '한국성서대학교', name: 'Korea Bible University' },
  { code: '한국승강기대학교', name: 'Korea Elevator College' },
  { code: '한국영상대학교', name: 'Korea University of Media Arts' },
  { code: '한국예술종합학교', name: 'Korea National University of Arts' },
  { code: '한국외국어대학교', name: 'Hankuk University of Foreign Studies' },
  {
    code: '한국전통문화대학교',
    name: 'Korea National University of Traditional Arts',
  },
  {
    code: '한국정보통신기능대학교',
    name: 'Korea Information and Communications University',
  },
  { code: '한국철도대학교', name: 'Korea Railroad College' },
  { code: '한국체육대학교', name: 'Korea National Sport University' },
  { code: '한국폴리텍대학교', name: 'Korea Polytechnics University' },
  { code: '한국항공대학교', name: 'Korea Aerospace University' },
  { code: '국립한국해양대학교', name: 'Korea Maritime & Ocean University' },
  { code: '한남대학교', name: 'Hannam University' },
  { code: '한동대학교', name: 'Handong Global University' },
  { code: '한라대학교', name: 'Halla University' },
  { code: '한려대학교', name: 'Hallyeo University' },
  {
    code: '한려대학교(산업대)',
    name: 'Hallyeo University (Industry University)',
  },
  { code: '한림대학교', name: 'Hallym University' },
  { code: '한림성심대학교', name: 'Hallym Sacred Heart University' },
  { code: '한민학교', name: 'Hanmin School' },
  { code: '한밭대학교', name: 'Hanbat National University' },
  {
    code: '한밭대학교(산업대)',
    name: 'Hanbat National University (Industry University)',
  },
  { code: '한북대학교', name: 'Hanbuk University' },
  { code: '한서대학교', name: 'Hanseo University' },
  { code: '한성대학교', name: 'Hansung University' },
  { code: '한세대학교', name: 'Hansei University' },
  { code: '한신대학교', name: 'Hanshin University' },
  { code: '한양대학교', name: 'Hanyang University' },
  { code: '한양대학교(ERICA)', name: 'Hanyang University (ERICA Campus)' },
  { code: '한양사이버대학교', name: 'Hanyang Cyber University' },
  { code: '한양여자대학교', name: "Hanyang Women's University" },
  { code: '한영대학교', name: 'Hanyoung University' },
  { code: '한영신학대학교', name: 'Hanyoung Theological University' },
  { code: '한일장신대학교', name: 'Hanil Presbyterian Theological Seminary' },
  { code: '한중대학교', name: 'Hanjung University' },
  { code: '협성대학교', name: 'Hyupsung University' },
  { code: '혜전대학교', name: 'Hyejeon University' },
  { code: '혜천대학교', name: 'Hyecheon University' },
  { code: '호남대학교', name: 'Honam University' },
  { code: '호남신학대학교', name: 'Honam Theological University' },
  { code: '호서대학교', name: 'Hoseo University' },
  { code: '호원대학교', name: 'Howon University' },
  { code: '홍익대학교', name: 'Hongik University' },
  { code: '홍익대학교(세종)', name: 'Hongik University (Sejong Campus)' },
  { code: '화신사이버대학교', name: 'Hwasein Cyber University' },
  {
    code: 'DGIST',
    name: 'DGIST (Daegu Gyeongbuk Institute of Science and Technology)',
  },
  { code: 'GIST', name: 'GIST (Gwangju Institute of Science and Technology)' },
  {
    code: 'KAIST',
    name: 'KAIST (Korea Advanced Institute of Science and Technology)',
  },
  {
    code: 'POSTECH',
    name: 'POSTECH (Pohang University of Science and Technology)',
  },
  {
    code: 'UNIST',
    name: 'UNIST (Ulsan National Institute of Science and Technology)',
  },
];

export default University;
