export { NotFound } from './notFound';
export { Home } from './home/home';
export { LandingPage } from './home/landingPage';
export { Login } from './auth/login';
export { ProfileSettings } from './auth/profileSettings';
export { AllBoard } from './board/allboard';
export { Terms } from './auth/terms';
export { Board } from './board/board'
export { MyPage } from './my/mypage';
export { Scrap } from './my/community/scrap';
export { MyArticle } from './my/community/myArticle';
export { BlockingManagement } from './my/etc/blockingManagement';
export { DeleteAccount } from './my/etc/deleteAccount';
export { MyInfo } from './my/settings/myInfo';
export { Notification } from './my/settings/notification';
export { SchoolVerification } from './my/settings/schoolVerification';
export { Search } from './search/Search';